markdown: kramdown
#markdown: redcarpet
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
permalink: /blog/:year/:month/:day/:title/
url: http://anotherbug.com
author: Shuangjiang Li
pygments: true
safe: true
paginate: 16
auto: true

